export const banks = [
    "Альфа-Банк [RU]",
    "Pasta",
    "Rietumu",
    "Тинькофф",
    "Альфа-Банк [KZ]",
    "РНКБ",
    "Сбербанк [KZ]",
    "Бинбанк",
    "Тинькофф-выплаты",
    "Тинькофф-AFT",
    "Сбербанк [RU]",
    "PayDoo",
    "PayDoo-выплаты",
    "БелГазПромБанк",
    "BelVeb",
    "eWayHK",
    "Moneta",
    "WireCard",
    "Русский Стандарт",
    "GlobalPayments",
    "PayClub",
    "Upc",
    "WinPay",
    "WinPayOut",
    "Сбербанк [RU] Rbs",
    "KuveitTurk",
    "MonetaPayOut",
    "MonetaV2",
    "Альфа-Банк [KZ] Rbs",
    "Тинькофф MAPI",
    "Тинькофф MAPI выплаты",
    "Альфа-Банк [BY] Rbs",
    "BePaid [BY]",
    "ВТБ",
    "PayGateway",
    "Connectum",
    "ConnectumPayOut",
    "MtsRbs",
    "Ziraat",
    "UpcPayout",
    "Kicb",
    "IdramBankRbs",
    "Paysage",
    "NetworkAe",
    "Mkb",
    "Oschad",
    "Jysan",
    "AmeriaRbs",
    "Kapital",
    "FreedomRbs",
    "FreedomPB",
    "Qiwi",
    "Банк ЦентрКредит",
    "СБП",
    "Unlimint",
    "BccPayout",
    "GazProm",
    "Рассрочка Тинькофф",
    "STP SPEI"
  ];